#       _____           _    _         _____ _ _      _               ______
#     / ____|          | |  (_)       / ____| (_)    | |             |___  /
#    | |     ___   ___ | | ___  ___  | |    | |_  ___| | _____ _ __     / /
#    | |    / _ \ / _ \| |/ / |/ _ \ | |    | | |/ __| |/ / _ \ '__|   / /
#    | |___| (_) | (_) |   <| |  __/ | |____| | | (__|   <  __/ |     / /__
#     \_____\___/ \___/|_|\_\_|\___|  \_____|_|_|\___|_|\_\___|_|    /_____|

# !!! COLOR CODES !!!
# This plugin supports old color codes like: &c, &l, &o, etc
# It also supports minimessage, which is a more advanced way to format messages:
# https://docs.advntr.dev/minimessage/format.html
# With these, you can also add HEX colors, gradients, hover and click events, etc

# If set to true, LifeStealZ will check for updates and let you know if there's a newer version
checkForUpdates: true

# Set the language to any code found in the "lang" folder (don't add the .yml extension)
# You can add your own language files. Use https://github.com/KartoffelChipss/LifeStealZ/tree/main/src/main/resources/lang/en-US.yml as a template
# If you want to help translating the plugin, please refer to this article: https://lsz.strassburger.dev/contributing/localization
lang: "en-US"

# The the cookie name
cookieName: "&7Cookies"

offlineCookies:
  # If set to true, players will earn cookies while they are offline
  enabled: true

  # Wether or not to send a message to the player when they join informing them about the cookies they earned while offline
  joinMessage: true


# === SOUNDS ===

# The sound that will be played when a player clicks a block
# You can find a list of sounds here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
clickSound: "BLOCK_WOODEN_BUTTON_CLICK_ON"

# The sound that will be played when a player buys an upgrade
upgradeSound: "ENTITY_PLAYER_LEVELUP"

# The sound that will be played when a player prestiges
prestigeSound: "ENTITY_PLAYER_LEVELUP"

# The sound when there was an error
errorSound: "ENTITY_VILLAGER_NO"


# === ANTICHEAT ===

anticheat:
  cps:
    # If set to true, the plugin will check for the amount of clicks per second
    enabled: true

    # The maximum amount of clicks per second a player is allowed to do
    max: 15

    # The message that will be sent to a player if they click too fast
    message: "&cYou are clicking too fast!"

    # The commands that will be executed if a player clicks too fast
    commands:
      #- "kick %player% &cYou are clicking too fast!"

  nomovement:
    # If set to true, the plugin will check if a player is moving
    enabled: true

    # The maximum amount of time a player is allowed to not move (in seconds)
    max: 15

    # The message that will be sent to a player if they are not moving
    message: "&cYou are not moving!"

    # The commands that will be executed if a player is not moving
    commands:
      # - "kick %player% &cYou are not moving!"


# === STORAGE ===

storage:
  # The type of storage to use. You have the following options:
  # "SQLite"
  type: "SQLite"

  # This section is only relevant if you use a MySQL database
  host: "localhost"
  port: 3306
  database: "cookieclicker"
  username: "root"
  password: "password"