name: CookieClickerZ
version: '${project.version}'
main: org.strassburger.cookieclickerz.CookieClickerZ
api-version: '1.20'
softdepend:
  - PlaceholderAPI
  - DecentHolograms
authors: [Kartoffelchipss]
description: A highly customizable Cookie Clicker plugin!
website: strassburger.org

commands:
  cookieclicker:
    aliases:
      - cookieclickerz
      - cc
    description: Main command

permissions:
  cookieclickerz.viewachievements:
    default: true
    description: Permission to view achievements
  cookieclickerz.useclicker:
    default: true
    description: Permission to use a clicker
  cookieclickerz.upgrades:
    default: true
    description: Permission to open the upgrade shop
  cookieclickerz.prestige:
    default: true
    description: Permission to open the prestige menu
  cookieclickerz.boosters:
    default: true
    description: Permission to open the booster menu
  cookieclickerz.top:
    default: true
    description: Permission to open the top players menu
  cookieclickerz.numcheatsheet:
    default: true
    description: Permission to use the number shorthand cheatsheet
  cookieclickerz.reload:
    default: op
    description: Permission to reload the plugin
  cookieclickerz.manageclickers:
    default: op
    description: Permission to add a clicker blocks
  cookieclickerz.managecookies:
    default: op
    description: Permission to manage cookies
  cookieclickerz.manageevents:
    default: op
    description: Permission to manage events
  cookieclickerz.manageachievements:
    default: op
    description: Permission to manage achievements