name: CookieClickerZ
version: '1.0.0'
main: org.strassburger.cookieclickerz.CookieClickerZ
api-version: '1.20'
softdepend: [PlaceholderAPI]
authors: [Kartoffelchipss]
description: A highly customizable Cookie Clicker plugin!
website: strassburger.org

commands:
  cookieclicker:
    aliases:
      - cookieclickerz
      - cc
    description: Main command

permissions:
  cookieclicker.manageclickers:
    default: op
    description: Permission to add a clicker blocks